//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopping.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebShopping.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Deletion complete.
        /// </summary>
        public static string AdminDelete {
            get {
                return ResourceManager.GetString("AdminDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin insertion is complete.
        /// </summary>
        public static string AdminInsert {
            get {
                return ResourceManager.GetString("AdminInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin insertion was a failure.
        /// </summary>
        public static string AdminInsertFail {
            get {
                return ResourceManager.GetString("AdminInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin doesn&apos;t exist.
        /// </summary>
        public static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&apos;s password reset is complete.
        /// </summary>
        public static string AdminPass {
            get {
                return ResourceManager.GetString("AdminPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot order less than 1 unit or more than 10 units of an item in a single Invoice.
        /// </summary>
        public static string AmountVali {
            get {
                return ResourceManager.GetString("AmountVali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string B2L {
            get {
                return ResourceManager.GetString("B2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Deletion complete.
        /// </summary>
        public static string CatDelete {
            get {
                return ResourceManager.GetString("CatDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category insertion complete.
        /// </summary>
        public static string CategoryInsert {
            get {
                return ResourceManager.GetString("CategoryInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required.
        /// </summary>
        public static string CategoryReq {
            get {
                return ResourceManager.GetString("CategoryReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category insertion was a failure.
        /// </summary>
        public static string CatInsertFail {
            get {
                return ResourceManager.GetString("CatInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category doesn&apos;t exist.
        /// </summary>
        public static string CatNotFound {
            get {
                return ResourceManager.GetString("CatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Category&apos;s name is already used.
        /// </summary>
        public static string CatUnique {
            get {
                return ResourceManager.GetString("CatUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Category is complete.
        /// </summary>
        public static string CatUpdate {
            get {
                return ResourceManager.GetString("CatUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Category was a failure.
        /// </summary>
        public static string CatUpdateFail {
            get {
                return ResourceManager.GetString("CatUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Deletion complete.
        /// </summary>
        public static string CusDelete {
            get {
                return ResourceManager.GetString("CusDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer insertion complete.
        /// </summary>
        public static string CusInsert {
            get {
                return ResourceManager.GetString("CusInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer insertion was a failure.
        /// </summary>
        public static string CusInsertFail {
            get {
                return ResourceManager.GetString("CusInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer doesn&apos;t exist.
        /// </summary>
        public static string CusNotFound {
            get {
                return ResourceManager.GetString("CusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer is complete.
        /// </summary>
        public static string CusUpdate {
            get {
                return ResourceManager.GetString("CusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Customer was a failure.
        /// </summary>
        public static string CusUpdateFail {
            get {
                return ResourceManager.GetString("CusUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date should not be past.
        /// </summary>
        public static string DateValiPast {
            get {
                return ResourceManager.GetString("DateValiPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Admin ?.
        /// </summary>
        public static string DelAdmin {
            get {
                return ResourceManager.GetString("DelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete The Boss, BOI.
        /// </summary>
        public static string DelBoss {
            get {
                return ResourceManager.GetString("DelBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DelConfirm {
            get {
                return ResourceManager.GetString("DelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Customer ?.
        /// </summary>
        public static string DelCustomer {
            get {
                return ResourceManager.GetString("DelCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Category ?.
        /// </summary>
        public static string DelDesc {
            get {
                return ResourceManager.GetString("DelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this customer&apos;s Invoice ?.
        /// </summary>
        public static string DelInv {
            get {
                return ResourceManager.GetString("DelInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Invoice item ?.
        /// </summary>
        public static string DelInvItem {
            get {
                return ResourceManager.GetString("DelInvItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Process.
        /// </summary>
        public static string DelOps {
            get {
                return ResourceManager.GetString("DelOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL ITEMS UNDER THIS CATEGORY WILL BE DELETED.
        /// </summary>
        public static string DelWarn {
            get {
                return ResourceManager.GetString("DelWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Total.
        /// </summary>
        public static string DiscountTotal {
            get {
                return ResourceManager.GetString("DiscountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is already used.
        /// </summary>
        public static string EmailUnique {
            get {
                return ResourceManager.GetString("EmailUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured.
        /// </summary>
        public static string ErrorEvent {
            get {
                return ResourceManager.GetString("ErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s Image.
        /// </summary>
        public static string ImgItem {
            get {
                return ResourceManager.GetString("ImgItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large, File limit is 4 MB.
        /// </summary>
        public static string ImgLarge {
            get {
                return ResourceManager.GetString("ImgLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File Formats are .jpg , .jpeg and .png.
        /// </summary>
        public static string ImgSupport {
            get {
                return ResourceManager.GetString("ImgSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Photo.
        /// </summary>
        public static string ImgUpdate {
            get {
                return ResourceManager.GetString("ImgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Image File Cannot exceeds 4 MB.
        /// </summary>
        public static string ImgWarn {
            get {
                return ResourceManager.GetString("ImgWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Deletion complete.
        /// </summary>
        public static string InvDelete {
            get {
                return ResourceManager.GetString("InvDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice insertion complete.
        /// </summary>
        public static string InvInsert {
            get {
                return ResourceManager.GetString("InvInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice insertion was a failure.
        /// </summary>
        public static string InvInsertFail {
            get {
                return ResourceManager.GetString("InvInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Item Deletion complete.
        /// </summary>
        public static string InvItemDelete {
            get {
                return ResourceManager.GetString("InvItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item you inserted is already in this Invoice.
        /// </summary>
        public static string InvItemExists {
            get {
                return ResourceManager.GetString("InvItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Item insertion complete.
        /// </summary>
        public static string InvItemInsert {
            get {
                return ResourceManager.GetString("InvItemInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add any item since there aren&apos;t any.
        /// </summary>
        public static string InvItemNoItems {
            get {
                return ResourceManager.GetString("InvItemNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Invoice Item doesn&apos;t exist.
        /// </summary>
        public static string InvItemNotFound {
            get {
                return ResourceManager.GetString("InvItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Item Update is complete.
        /// </summary>
        public static string InvItemUpdate {
            get {
                return ResourceManager.GetString("InvItemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add any invoice because you don&apos;t have any customers.
        /// </summary>
        public static string InvNoCustomers {
            get {
                return ResourceManager.GetString("InvNoCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice was not found.
        /// </summary>
        public static string InvNotFound {
            get {
                return ResourceManager.GetString("InvNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Of.
        /// </summary>
        public static string InvoicesOf {
            get {
                return ResourceManager.GetString("InvoicesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Invoice is complete.
        /// </summary>
        public static string InvUpdate {
            get {
                return ResourceManager.GetString("InvUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Invoice was a failure.
        /// </summary>
        public static string InvUpdateFail {
            get {
                return ResourceManager.GetString("InvUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item only have.
        /// </summary>
        public static string ItemAmount {
            get {
                return ResourceManager.GetString("ItemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Items without at least 1 Category inserted.
        /// </summary>
        public static string ItemCatWarning {
            get {
                return ResourceManager.GetString("ItemCatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Item ?.
        /// </summary>
        public static string ItemDel {
            get {
                return ResourceManager.GetString("ItemDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deletion complete.
        /// </summary>
        public static string ItemDelete {
            get {
                return ResourceManager.GetString("ItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item insertion complete.
        /// </summary>
        public static string ItemInsert {
            get {
                return ResourceManager.GetString("ItemInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item insertion was a failure.
        /// </summary>
        public static string ItemInsertFail {
            get {
                return ResourceManager.GetString("ItemInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Items.
        /// </summary>
        public static string ItemNos {
            get {
                return ResourceManager.GetString("ItemNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was not found.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s Photo Update complete.
        /// </summary>
        public static string ItemPhotoUpdate {
            get {
                return ResourceManager.GetString("ItemPhotoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s Photo Update was a failure.
        /// </summary>
        public static string ItemPhotoUpdateFail {
            get {
                return ResourceManager.GetString("ItemPhotoUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items For.
        /// </summary>
        public static string ItemsFor {
            get {
                return ResourceManager.GetString("ItemsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Update complete.
        /// </summary>
        public static string ItemUpdate {
            get {
                return ResourceManager.GetString("ItemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Update was a failure.
        /// </summary>
        public static string ItemUpdateFail {
            get {
                return ResourceManager.GetString("ItemUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&apos;s name successfully changed.
        /// </summary>
        public static string NameChange {
            get {
                return ResourceManager.GetString("NameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must contain only letters and be at least 3 characters long..
        /// </summary>
        public static string NameVali {
            get {
                return ResourceManager.GetString("NameVali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Again.
        /// </summary>
        public static string NewPasswordAgain {
            get {
                return ResourceManager.GetString("NewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add an item to this Invoice because no item exist, Please Add items to continue.
        /// </summary>
        public static string NoItemWarning {
            get {
                return ResourceManager.GetString("NoItemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Ops {
            get {
                return ResourceManager.GetString("Ops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&apos;s password was successfully changed.
        /// </summary>
        public static string PassChanged {
            get {
                return ResourceManager.GetString("PassChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either The email or the password is invalid.
        /// </summary>
        public static string PasswordLog {
            get {
                return ResourceManager.GetString("PasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one digit..
        /// </summary>
        public static string PasswordVali {
            get {
                return ResourceManager.GetString("PasswordVali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string PhoneVali {
            get {
                return ResourceManager.GetString("PhoneVali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Of.
        /// </summary>
        public static string PhotoOf {
            get {
                return ResourceManager.GetString("PhotoOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPass {
            get {
                return ResourceManager.GetString("ResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        public static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Heaven Store.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 minutes of inactivites has passed, Do you want to continue ?.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning !.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password is incorrect.
        /// </summary>
        public static string WrongPass {
            get {
                return ResourceManager.GetString("WrongPass", resourceCulture);
            }
        }
    }
}
